version: "3.7"

services:
  app:
    build: .
    container_name: "backend"
    restart: "always"
    expose:
      - "8000"
    volumes:
      - type: "bind"
        source: "./core"
        target: "/app"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
  nginx:
    build: "./nginx"
    container_name: "nginx"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - type: "bind"
        source: "./core/staticfiles"
        target: "/app/static"

      - type: "bind"
        source: "./core/media"
        target: "/app/media"
