# Generated by Django 5.1.1 on 2024-10-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_oreder_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oreder',
            name='buyer',
        ),
    ]
